#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" app
usermod -o -u "$PUID" app

echo '
----------------------------------------------------------------------------
GID/UID
----------------------------------------------------------------------------'
echo "
User uid:    $(id -u app)
User gid:    $(id -g app)
----------------------------------------------------------------------------
"
chown app:app /var/www
chown app:app /config
chown app:app /defaults
